# Generated by Django 2.1.3 on 2018-11-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arriving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardNumber', models.CharField(db_index=True, max_length=150)),
                ('from_at', models.CharField(db_index=True, max_length=150)),
                ('startTime', models.CharField(db_index=True, max_length=150)),
                ('to', models.CharField(db_index=True, max_length=150)),
                ('endTime', models.CharField(db_index=True, max_length=150)),
                ('status', models.CharField(db_index=True, max_length=150)),
            ],
        ),
    ]
